[package]
name = "microbit-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
armv6-m = { path = "../microbit-vm/lib/armv6-m" }
byteorder = "1.4.3"
